//Testbench generated by AI.

module fifo_tb;

    localparam WIDTH = 8;
    localparam DEPTH = 4;

    logic             clk;
    logic             rst;

    logic             wr_valid;
    logic             wr_ready;
    logic [WIDTH-1:0] wr_data;

    logic             rd_valid;
    logic             rd_ready;
    logic [WIDTH-1:0] rd_data;

    fifo #(
        .WIDTH(WIDTH),
        .DEPTH(DEPTH)
    ) dut (
        .clk(clk),
        .rst(rst),

        .wr_valid(wr_valid),
        .wr_ready(wr_ready),
        .wr_data (wr_data),

        .rd_valid(rd_valid),
        .rd_ready(rd_ready),
        .rd_data (rd_data)
    );


    // Clock
    initial begin
        clk = 0;
        forever #5 clk = ~clk;
    end


    // Test
    initial begin

        wr_valid = 0;
        wr_data  = 0;
        rd_ready = 0;
        rst      = 1;

        // Hold reset for a couple cycles
        repeat (2) @(posedge clk);
        rst = 0;

        // --------------------------------------------------
        // Write 4 bytes
        // --------------------------------------------------

        $display("Writing bytes...");

        write_byte(8'hAA);
        write_byte(8'hBB);
        write_byte(8'hCC);
        write_byte(8'hDD);

        // FIFO should now be full
        @(posedge clk);
        #1;

        assert (wr_ready == 0)
        else $error("FIFO should be full!");

        assert (rd_valid == 1)
        else $error("FIFO should not be empty!");


        // --------------------------------------------------
        // Read them back
        // --------------------------------------------------

        $display("Reading bytes...");

        read_byte(8'hAA);
        read_byte(8'hBB);
        read_byte(8'hCC);
        read_byte(8'hDD);

        // FIFO should now be empty
        @(posedge clk);
        #1;

        assert (rd_valid == 0)
        else $error("FIFO should be empty!");


        // --------------------------------------------------
        // Simultaneous read/write
        // --------------------------------------------------

        $display("Testing simultaneous read/write...");

        write_byte(8'h11);
        write_byte(8'h22);

        // Both sides active
        @(negedge clk);

        wr_valid = 1;
        wr_data  = 8'h33;

        rd_ready = 1;

        @(posedge clk);
        #1;

        // 11 should have been read
        assert (rd_data == 8'h22)
        else $error("Expected 0x22 after simultaneous read/write, got %h", rd_data);

        wr_valid = 0;
        rd_ready = 0;


        // --------------------------------------------------
        // Finish
        // --------------------------------------------------

        $display("TEST PASSED");

        #20;
        $finish;
    end


    // ------------------------------------------------------
    // Write one byte
    // ------------------------------------------------------

    task write_byte(input logic [WIDTH-1:0] data);
        begin
            @(negedge clk);

            wr_data  = data;
            wr_valid = 1;

            // Wait until transfer occurs
            while (!wr_ready) @(negedge clk);

            // The transfer happens at the next posedge
            @(negedge clk);

            wr_valid = 0;
        end
    endtask


    // ------------------------------------------------------
    // Read one byte and check it
    // ------------------------------------------------------

    task read_byte(input logic [WIDTH-1:0] expected);
        begin
            @(negedge clk);

            rd_ready = 1;

            // Wait until data is available
            while (!rd_valid) @(negedge clk);

            // Data must be valid before the consuming edge
            assert (rd_data == expected)
            else $error("Expected %h, got %h", expected, rd_data);

            // Let DUT consume it
            @(negedge clk);

            rd_ready = 0;
        end
    endtask

endmodule
